// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://cxuwxijzufjeyijczodx.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN4dXd4aWp6dWZqZXlpamN6b2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzIzNDg4MTksImV4cCI6MjA0NzkyNDgxOX0.io_XwQqjeuQvkd3Swb1kmsj8tjhLTFdnoJIGaafHchE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);